// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(PegiDbContext))]
    [Migration("20221111163336_modifyPerson")]
    partial class modifyPerson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.AcademicProgram", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code_program");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_academics_program");

                    b.ToTable("academics_program", (string)null);
                });

            modelBuilder.Entity("Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city_id");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("department_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city_name");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("DepartmentCode")
                        .HasDatabaseName("ix_cities_department_code");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("deparment_name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Entities.Experience", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("experience_code");

                    b.Property<string>("CitiesCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cities_code");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("study_end_date");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("experience_institution");

                    b.Property<string>("PeopleCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("people_code");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("experience_position");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("study_start_date");

                    b.HasKey("Code")
                        .HasName("pk_experiences");

                    b.HasIndex("CitiesCode")
                        .HasDatabaseName("ix_experiences_cities_code");

                    b.HasIndex("PeopleCode")
                        .HasDatabaseName("ix_experiences_people_code");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<string>("Document")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("person_document");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("person_birth_date");

                    b.Property<string>("CitiesCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cities_code");

                    b.Property<string>("CivilState")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_civil_state");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_first_last_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_gender");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_identification_type");

                    b.Property<string>("InstitutionalMail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_institutional_email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("person_phone");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("longtext")
                        .HasColumnName("person_second_last_name");

                    b.Property<string>("SecondName")
                        .HasColumnType("longtext")
                        .HasColumnName("person_second_name");

                    b.HasKey("Document")
                        .HasName("pk_people");

                    b.HasIndex("CitiesCode")
                        .HasDatabaseName("ix_people_cities_code");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Entities.Study", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("study_code");

                    b.Property<string>("CitiesCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cities_code");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("study_end_date");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("study_institution");

                    b.Property<string>("PeopleCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("people_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("study_start_date");

                    b.HasKey("Code")
                        .HasName("pk_studies");

                    b.HasIndex("CitiesCode")
                        .HasDatabaseName("ix_studies_cities_code");

                    b.HasIndex("PeopleCode")
                        .HasDatabaseName("ix_studies_people_code");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_rol");

                    b.Property<string>("person_document")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("person_document");

                    b.HasKey("Name")
                        .HasName("pk_users");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.HasIndex("person_document")
                        .HasDatabaseName("ix_users_person_document");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Entities.Professor", b =>
                {
                    b.HasBaseType("Entities.Person");

                    b.Property<int>("AmountCredits")
                        .HasColumnType("int")
                        .HasColumnName("amount_credits");

                    b.ToTable("professor");
                });

            modelBuilder.Entity("Entities.Student", b =>
                {
                    b.HasBaseType("Entities.Person");

                    b.Property<int>("AmountCredits")
                        .HasColumnType("int")
                        .HasColumnName("amount_credits");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("longtext")
                        .HasColumnName("program_code");

                    b.Property<string>("academic_program_code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("academic_program_code");

                    b.HasIndex("academic_program_code")
                        .HasDatabaseName("ix_students_academic_program_code");

                    b.ToTable("students");
                });

            modelBuilder.Entity("Entities.City", b =>
                {
                    b.HasOne("Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cities_departments_department_code");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Entities.Experience", b =>
                {
                    b.HasOne("Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CitiesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experiences_cities_cities_code");

                    b.HasOne("Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PeopleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experiences_people_people_code");

                    b.Navigation("City");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CitiesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_people_cities_cities_code");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Entities.Study", b =>
                {
                    b.HasOne("Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CitiesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studies_cities_cities_code");

                    b.HasOne("Entities.Person", "Person")
                        .WithMany("Studies")
                        .HasForeignKey("PeopleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studies_people_people_code");

                    b.Navigation("City");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.HasOne("Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("person_document")
                        .HasConstraintName("fk_users_people_person_document");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Professor", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Entities.Professor", "Document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professor_people_person_document");
                });

            modelBuilder.Entity("Entities.Student", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("Entities.Student", "Document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_people_person_document");

                    b.HasOne("Entities.AcademicProgram", "AcademicProgram")
                        .WithMany()
                        .HasForeignKey("academic_program_code")
                        .HasConstraintName("fk_students_academics_program_academic_program_code");

                    b.Navigation("AcademicProgram");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Navigation("Studies");
                });
#pragma warning restore 612, 618
        }
    }
}
